---
title: "Using the Household Package"
author: "Brian Gregor"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using the Household Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The **household** package contains several models for the RSPM framework. The goals of these models are to synthesize a set of households which realistically represent a population projection of persons by age group, an income forecast for the area, and a land use forecast. The models in this package include:  

- **SynthesizeHh**: This model creates a synthetic population of households which represent a demographic forecast of number of persons by age group, and which represent the makeup of households found in the region. The *SynthesizeHh* vignette describes this model and what to do to use it.

- **PredictIncome**: This model assigns an annual income to each household based on the age composition and a projection of average per capita income for the area. The model picks the household income from a distribution of incomes to reproduce the variation found in the population. The *PredictIncome* vignette describes this model and what to do to use it.  

- **AssignLandUse**: This model assigns land use characteristics to each household including the district where the household is placed, the density of the district, a housing type (e.g. single family, multi-family), and a place type (e.g. mixed-use, suburban, rural). The *AssignLandUse* vignette describes this model and what to do to use it.

Each of these models includes parameters that must be estimated in order to reflect conditions in the region being modeled. To do this, the user will have to work with the source version of this package. They will have to gather certain information about their region, place it in properly formatted files, and save it in the *inst/extdata* directory. The vignette for each model describes must be done in detail.

After everything has been done to prepare the data needed to estimate parameters for the region, the modified source package must be built as a binary package. I highly recommend that you do this using the RStudio IDE for R development along with the *devtools* package. RStudio is free and it along with *devtools* has everything you need to easily create a binary package from a source package. The `devtools::build(binary = TRUE)` will take care of things. For more information about R packages, I recommend referring to Hadley Wickham's book, *R Packages*, and/or to his [website](http://r-pkgs.had.co.nz/).
