---
title: "Using the vedemo1 Package"
author: "Brian Gregor"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using the vedemo1 Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The **vedemo1** package contains several demonstration modules for the VisionEval framework. These modules were developed to work with minimally specified geography. In other words, only Azones and Mareas are specified. The modules create a simulated set of households, simulated Bzones, and simulated Bzone development characteristics. The package demonstrates several aspects of how goals of these models are to synthesize a set of households which realistically represent a population projection of persons by age group, an income forecast for the area, and a land use forecast. The models in this package include:  

- **CreateHouseholds**: This demonstration module creates simulated households for a model where geography is minimally specified, i.e. where only Azones and Mareas are specified. Simulated households are created using a household size distribution for the model area and Azone populations. The module creates a dataset of household sizes. A 'Households' table is initialized and populated with the household size dataset. Azone locations and household IDs are also added to the Household table.
The *CreateHouseholds* vignette describes this model and how region-specific inputs can be used to create a model which represents the region.

- **CreateBzones**: This demonstration module creates simulated Bzones that have a specified numbers of households and development types (Metropolitan, Town, Rural). Module determines the number of Bzones in each Azone and assigns a unique ID and a development type to each. It also calculates the number of households in each Bzone such that the proportion of households in each Azone assigned to each development type matches assumed input proportions. It also assigns the respective Mareas to the simulated Bzones. A Bzone table is created and populated with unique IDs, development types, Mareas, Azones, and numbers of households. The *CreateBzones* vignette describes this model and what to do to use it.

- **CreateBzoneDev**: This module simulates development characteristics for each Bzone. These characteristics include the population density (persons per square mile), the number of single-family detached dwelling units, and the number of multifamily dwelling units. In addition, for Bzones that are designated as 'Metropolitan' it assigns a distance to the urban core. The *CreateBzoneDev* vignette describes this model and what to do to use it.

Two of these modules (CreateHouseholds, CreateBzoneDev) include parameters that may be estimated in order to reflect conditions in the region being modeled. To do this, the user will have to work with the source version of this package. They will have to gather certain information about their region, place it in properly formatted files, and save it in the *inst/extdata* directory. The vignette for each module describes must be done in detail.

After everything has been done to prepare the data needed to estimate parameters for the region, the modified source package must be built as a binary package. The best way to do this is using the RStudio IDE for R development along with the *devtools* package. RStudio is free and it along with *devtools* has everything you need to easily create a binary package from a source package. The `devtools::build(binary = TRUE)` will take care of things. For more information about R packages, I recommend referring to Hadley Wickham's book, *R Packages*, and/or to his [website](http://r-pkgs.had.co.nz/).
